### ISSUE TITLE
points.geometry has duplicated records

### ISSUE THREAD

**Issue by kj-9** [kj-9/jma-data#7]
```
$ splite 'select count(1), count(distinct geometry) from points'
[{"count(1)": 779904, "count(distinct geometry)": 32496}]
```

no unique constraint on geometry.points so far.

so if there is any update, always inserts all geometry feature to points.

**Comment by kj-9** [comment]
this is reasonable way:
https://gis.stackexchange.com/questions/285020/unique-constraint-for-spatiallite-geometry-column

(creating unique index on points.geometry)

but it fails:

```
 splite 'CREATE UNIQUE INDEX point_geometry_uq_idx ON points(geometry)';       
Traceback (most recent call last):
  File "/Users/kh03/work/repos/jma-data/.venv/bin/sqlite-utils", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/kh03/work/repos/jma-data/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kh03/work/repos/jma-data/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/kh03/work/repos/jma-data/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kh03/work/repos/jma-data/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kh03/work/repos/jma-data/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kh03/work/repos/jma-data/.venv/lib/python3.12/site-packages/sqlite_utils/cli.py", line 1801, in query
    _execute_query(
  File "/Users/kh03/work/repos/jma-data/.venv/lib/python3.12/site-packages/sqlite_utils/cli.py", line 2031, in _execute_query
    cursor = db.execute(sql, dict(param))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kh03/work/repos/jma-data/.venv/lib/python3.12/site-packages/sqlite_utils/db.py", line 524, in execute
    return self.conn.execute(sql, parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: points.geometry
```

need to migrate duplicated records first!

**Comment by kj-9** [comment]
migrate.sh:
```sh
#!/bin/bash

set -eu -o pipefail

# constants
FILE_DB_GZ="data/jma.db.gz"
FILE_DB="data/jma.db"
FILE_DB_OLD="data/jma-old.db"

# alias
splite() {
    sqlite-utils --load-extension=spatialite --attach old "$FILE_DB_OLD" "$FILE_DB" "$@"
}

du -h $FILE_DB_GZ
gunzip -fkc $FILE_DB_GZ > $FILE_DB_OLD

bash scripts/init-db.sh


splite  '
insert into dates (valid_date)
select valid_date from old.dates
'

splite '
insert into points (geometry)
select distinct geometry from old.points
'

splite '
insert into temperature (date_id, point_id, min_temp)
with min_temp_uq as (
select date_id, geometry, max(point_id) as point_id
from old.temperature
   left join old.points using (point_id)
where min_temp is not null
group by date_id, geometry
)
select date_id, points.point_id, min_temp
from old.temperature
   inner join min_temp_uq using (date_id, point_id)
   left join points using (geometry)
order by date_id, points.point_id
'

splite '
insert into temperature (date_id, point_id, max_temp)
with max_temp_uq as (
select date_id, geometry, max(point_id) as point_id
from old.temperature
   left join old.points using (point_id)
where max_temp is not null
group by date_id, geometry
)
select date_id, points.point_id, max_temp
from old.temperature
   inner join max_temp_uq using (date_id, point_id)
   left join points using (geometry)
order by date_id, points.point_id
on conflict (date_id, point_id) do update set max_temp = excluded.max_temp
'

sqlite-utils vacuum $FILE_DB

gzip -kf $FILE_DB
du -h $FILE_DB_GZ
```
in this script:
- gunzip existing db.gz to `jma-old.db` file
- create new empty `jma.db` file `` from new version of `init-db.sh`
- then attach `jma-old.db` as `old` schema and run upserts to new empty tables

**Comment by kj-9** [comment]
```
$ bash scripts/migrate.sh 
 34M    data/jma.db.gz
create if not exists `dates` table...
[{"rows_affected": -1}]
create if not exists `points` table...
[{"rows_affected": -1}]
[{"AddGeometryColumn('points', 'geometry', 4326, 'POINT', 2, 1)": 1}]
[{"rows_affected": -1}]
create if not exists `temperature` table...
[{"rows_affected": -1}]
[{"rows_affected": 9}]
[{"rows_affected": 32496}]
[{"rows_affected": 259968}]
[{"rows_affected": 292464}]
4.1M    data/jma.db.gz
```

also greatly reduced file size 34M to 4M in gz, refs #6

**Comment by kj-9** [comment]
[now works fine](https://github.com/kj-9/jma-data/actions/runs/10878662386/job/30181933464)
